// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcppParse
void rcppParse(std::string js);
RcppExport SEXP _mapboxGeojson_rcppParse(SEXP jsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type js(jsSEXP);
    rcppParse(js);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mapboxGeojson_rcppParse", (DL_FUNC) &_mapboxGeojson_rcppParse, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mapboxGeojson(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
