# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppParseFeature <- function(js) {
    invisible(.Call('_mapboxGeojson_rcppParseFeature', PACKAGE = 'mapboxGeojson', js))
}

rcppParseGeometry <- function(js) {
    invisible(.Call('_mapboxGeojson_rcppParseGeometry', PACKAGE = 'mapboxGeojson', js))
}

rcppParseLineString <- function(js) {
    .Call('_mapboxGeojson_rcppParseLineString', PACKAGE = 'mapboxGeojson', js)
}

template_point <- function() {
    .Call('_mapboxGeojson_template_point', PACKAGE = 'mapboxGeojson')
}

template_linestring <- function() {
    .Call('_mapboxGeojson_template_linestring', PACKAGE = 'mapboxGeojson')
}

MultiPolygonCoordinates <- function(js) {
    .Call('_mapboxGeojson_MultiPolygonCoordinates', PACKAGE = 'mapboxGeojson', js)
}

