# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_geojson_to_sf <- function(geojson) {
    .Call('_mapboxGeojson_rcpp_geojson_to_sf', PACKAGE = 'mapboxGeojson', geojson)
}

rcppParseFeature <- function(js) {
    invisible(.Call('_mapboxGeojson_rcppParseFeature', PACKAGE = 'mapboxGeojson', js))
}

rcppParseGeometry <- function(js) {
    invisible(.Call('_mapboxGeojson_rcppParseGeometry', PACKAGE = 'mapboxGeojson', js))
}

rcppParseLineString <- function(js) {
    .Call('_mapboxGeojson_rcppParseLineString', PACKAGE = 'mapboxGeojson', js)
}

template_point <- function() {
    .Call('_mapboxGeojson_template_point', PACKAGE = 'mapboxGeojson')
}

template_multi_point <- function() {
    .Call('_mapboxGeojson_template_multi_point', PACKAGE = 'mapboxGeojson')
}

template_linestring <- function() {
    .Call('_mapboxGeojson_template_linestring', PACKAGE = 'mapboxGeojson')
}

template_multilinestring <- function() {
    .Call('_mapboxGeojson_template_multilinestring', PACKAGE = 'mapboxGeojson')
}

template_polygon <- function() {
    .Call('_mapboxGeojson_template_polygon', PACKAGE = 'mapboxGeojson')
}

template_multipolygon <- function() {
    .Call('_mapboxGeojson_template_multipolygon', PACKAGE = 'mapboxGeojson')
}

MultiPolygonCoordinates <- function(js) {
    .Call('_mapboxGeojson_MultiPolygonCoordinates', PACKAGE = 'mapboxGeojson', js)
}

mapbox_to_sfg <- function() {
    .Call('_mapboxGeojson_mapbox_to_sfg', PACKAGE = 'mapboxGeojson')
}

