# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testFeature <- function(geojson) {
    invisible(.Call('_mapboxGeojson_testFeature', PACKAGE = 'mapboxGeojson', geojson))
}

testFeatureCollection <- function(geojson) {
    invisible(.Call('_mapboxGeojson_testFeatureCollection', PACKAGE = 'mapboxGeojson', geojson))
}

